### ISSUE TITLE
Support scaling to deal with different screen sizes

### ISSUE THREAD

**Issue by Abreuvoir** [Apostolique/Apos.Gui#1]
Global scaling for the UI would be fine, per widget scaling may be interesting too.
Different filters may be necessary perhaps (ie nearest for pixel fonts, etc.)

**Comment by Apostolique** [comment]
My current idea to solve this is to do it from the SpriteBatch side. I can easily use a scale matrix to make everything drawn bigger without the Components having to be aware of any size changes.

To keep everything responsive, it's just a matter of projecting the window size down to this new UI space. Also need to provide ways to get mouse coordinates in this new UI space for components to use.

Doing it this way would allow scaling using float values which gives a lot of control.

This solves the scaling problem, but it might make some stuff look bad, for example bitmap fonts to write text. The Bitmap font would look pretty bad at a bigger scale. I will have to look for better font rendering techniques.

**Comment by Apostolique** [comment]
e33ff6acf1d05508646afb8c1d42a092ce275721 did the first part of UI scaling. Currently done via the `GuiHelper.Scaling` variable.

Per component scaling isn't as trivial. That could be left to whoever codes a component.

Filters can be done by modifying the Begin function from GuiHelper. It should pass in different arguments to the SpriteBatch.Begin.

**Comment by Apostolique** [comment]
a6fb6b8f5abead5ccee22c198ea2edcebc928038 should have this covered.

**Comment by Apostolique** [comment]
For the future, if per component scaling is required. There's a way to implement it without too much hassle.

1) Provide an overload for `GuiHelper.SetScissor()` that takes a scale parameter. Implicitly, it will call a different begin and set the Scissor accordingly.
2) Provide an overload for `GuiHelper.MouseToUI()` that takes a scale parameter.
