### ISSUE TITLE
Resolution change

### ISSUE THREAD

**Issue by RegalFenster** [Apostolique/Apos.Gui#11]
Hi,

I was wondering what the intended way to change resolution is right now? I found an old issue about this topic, but it seems a bit dated: https://github.com/Apostolique/Apos.Gui/issues/1
could you give me a small example how to use PushScissor()?

Thanks a lot! :)

**Comment by Apostolique** [comment]
Hey! You can change the scale with `GuiHelper.Scale`.

For the PushScissor, usually you'll pass the clipping rect of the component that you're drawing. You don't have to consider the scale.

You can see an example in Icon: <https://github.com/Apostolique/Apos.Gui/blob/main/Source/Icon.cs>

```cs
public override void Draw(GameTime gameTime) {
    GuiHelper.PushScissor(Clip);

    int halfWidth = (int)(Width / 2);
    int iconHalfWidth = (int)(PrefWidth / 2);

    int halfHeight = (int)(Height / 2);
    int iconHalfHeight = (int)(PrefHeight / 2);

    Vector2 pos = new(Left + halfWidth - iconHalfWidth, Top + halfHeight - iconHalfHeight);

    GuiHelper.SpriteBatch.Draw(Region, pos, Color.White);

    GuiHelper.PopScissor();
}
```

You can try this for example:

```cs
private float _slider = 1f;

// ...

Slider.Put(ref _slider, 1f, 3f, 0.1f);
GuiHelper.Scale = _slider;
```

**Comment by RegalFenster** [comment]
Thanks a lot for the answer!
