### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by QuinnBast** [Apostolique/Apos.Gui#5]
Hello,

This looks like a really good library. Unfortunately, I cannot seem to get it to load my ttf font file. This is a problem on my end, I'm just not sure how to resolve it...

`GuiHelper.Font = DynamicSpriteFont.FromTtf(File.ReadAllBytes(Content.RootDirectory + "/Assets/Fonts/Capsuula.ttf"), 30);`

When it tries to read the file it throws
![image](https://user-images.githubusercontent.com/22599103/69486872-84e6a980-0e16-11ea-84ae-0cd754d1f466.png)

File structure:
![image](https://user-images.githubusercontent.com/22599103/69486875-8f08a800-0e16-11ea-91eb-8d450be51c3d.png)

Pipeline:
![image](https://user-images.githubusercontent.com/22599103/69486878-a5166880-0e16-11ea-85b0-458abaf2a5a7.png)

Any thoughts?

**Comment by Apostolique** [comment]
The code I use in my game is this:
```csharp
using MemoryStream ms = new MemoryStream();
TitleContainer.OpenStream($"{Content.RootDirectory}/Assets/Fonts/Capsuula.ttf").CopyTo(ms);
byte[] fontBytes = ms.ToArray();
DynamicSpriteFont font = DynamicSpriteFont.FromTtf(fontBytes, 30);
```

Edit: Alternatively, there's a working example project here: https://github.com/Apostolique/AposGameStarter

I load the font in: https://github.com/Apostolique/AposGameStarter/blob/master/Assets.cs

**Comment by QuinnBast** [comment]
The code above helped get around the directory not found issue wonderfully to load my .ttf font. Thanks!

**Comment by Apostolique** [comment]
Nice! Yeah, I got that error a while ago. If I remember correctly, it happens when the root directory isn't right for example during development in vscode, the root directory can be the csproj's directory or something like that.
